### ISSUE TITLE
Server cache suport

### ISSUE THREAD

**Issue by eshengsky** [expressjs/serve-static#101]
* Does it read a file from disk every time? 
* Is it necessary to cache file to memory? (for example: the first request will read file from disk, and next requests will read from memory)
* If necessary, how to implement it?
Thanks!

**Comment by dougwilson** [comment]
Hi @eshengsky yes, this module will read the file from the disk for every request. This is by design because you're allowed to constantly change the underlying files. For example, users upload files into a directly (and even change their contents) and they should be available immediately.

If you have a use-case where the files are static and never change, you don't want to use Node.js to server them, period. Node.js does not use asyc file I/O APIs with the kernel, instead using a thread pool to do sync file I/O operations, which is very heavy and slow. I suggest using NGINX to serve static files.

I hope this helps!
