### ISSUE TITLE
A 304 response incorrectly includes Content-Length header

### ISSUE THREAD

**Issue by thernstig** [expressjs/serve-static#131]
By default, if I get a 304 response for a static asset it returns as an example:

```sh
Content-Length: 684
Content-Type: image/svg+xml
```

If I set an option on the express.static it however does not include those two headers. E.g. if I just try and set this on the express.static function:

```javascript
const options = {
  setHeaders(res) {
    res.set('x-timestamp', Date.now());
  },
};
```

A 304 should include these headers, see https://tools.ietf.org/html/rfc7232#section-4.1

**Comment by dougwilson** [comment]
Hello! Thanks for the issue report. I am a bit confused on the issue, if you can clarify. The title of the issue and the body of the issue seem different. Can you clarify on what the issue is between the title / body?

**Comment by dougwilson** [comment]
I just did a simple test using the https://github.com/expressjs/serve-static#simple example in the README and there was no Content-Length header in the 304 response I got. Can you show the specific code you are using that I can run to reproduce the issue and the specific request you make to get a 304 back with the header field? You can add that `x-timestamp` part in the example as well to demonstrate 👍

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by thernstig** [comment]
@dougwilson That is fair, I'll still re-investigate this soon and come back with a reply on my findings.

**Comment by dougwilson** [comment]
Hi @thernstig if you post here with additional information I can always re-open the issue. You're also welcome to open a new issue as well, just don't have anything to act on currently since I cannot reproduce your issue.

**Comment by thernstig** [comment]
@dougwilson I did a few trial and errors and decided to update the original answer with the core of the problem.

**Comment by dougwilson** [comment]
Thanks for the update. All those "extra" headers there are not being generated by this module or Express. Maybe some other middleware you are using? If that is the case, you may want to open an issue with the module that is generating those headers on a 304 if you believe that should not be the case.

**Comment by dougwilson** [comment]
Well Express (or Node.js) would clean up headers if they were MUST NOT, but what you quoted is SHOULD NOT; the spec allows any additional headers without it being a violation, just not suggested. There are different headers that override that as well, so if the example is Accept-Ranges that is fair; would need to look into what the definition of that header says about 304s.

**Comment by dougwilson** [comment]
Ok, so looking into it, here is the specific wording of RFC 7232 you quoted above:

>    Since the goal of a 304 response is to minimize information transfer
   when the recipient already has one or more cached representations, a
   sender SHOULD NOT generate representation metadata other than the
   above listed fields unless said metadata exists for the purpose of
   guiding cache updates

Since the text did not say like "headers" or something, instead it says "representation metadata", I went to look though the HTTP RFCs to see what, specifically, "representation metadata" is. I acknowledge that you are claiming it to be 1:1 with header fields, though I see just in RFC 7230 it lists "representation metadata" as one of three types of header fields:

>    A server responds to a client's request by sending one or more HTTP
   response messages, each beginning with a status line that includes
   the protocol version, a success or error code, and textual reason
   phrase (Section 3.1.2), possibly followed by header fields containing
   server information, resource metadata, and representation metadata
   (Section 3.2), an empty line to indicate the end of the header
   section, and finally a message body containing the payload body (if
   any, Section 3.3).

I'm trying to understand what are the differences between the tree different things headers can be and determine which one Accept-Ranges falls into. If it is not representation metadata, and instead server information or resource metadata, including it would not even fall within the SHOULD NOT in the 304 text.

**Comment by thernstig** [comment]
@dougwilson First of, thank you for the amazing patience, you're a stellar guy for sure. Yes, I agree it's not super clear, and it maybe is not a huge deal, but I was confused by all the headers and thought it warrented an issue to clear it up. I think you've gone above and beyond to show that this might be fine what I see, although we are unclear of what representation metadata is.
