### ISSUE TITLE
Security fix

### ISSUE THREAD

**Issue by troch** [expressjs/serve-static#143]
Hello 👋 

I'd like to contribute to this repository to fix a potential attack vector.
I'm ready to make a PR for it, but I'd rather not disclose what the issue is before knowing if it can be merged and released in a timely manner first. Is there a maintainer who could lead a patch release for this package and express? maybe discuss it first?

**Comment by dougwilson** [comment]
Hi, and thanks for reaching out. I really appreciate your willingness to work qith us on this. Please send me what the issue is, a PoC for the issur if you have one, and the patch so I can share with the team for review. You can find my email in the package.json and the license for thia module.

Once I get it and forward, we will evaluate the report to see if it is a security vulnerability or not. If so, we will work with you to coordinate releasing and, and if not you can open the or pubically.
