### ISSUE TITLE
Do not use Object.create to copy options

### ISSUE THREAD

**Issue by cppleon** [expressjs/serve-static#147]
```
var options = { etag: false }

// copy options object
var opts = Object.create(options || null)

console.log(opts)
```
Expected behaviour: `{etag: false}`
Actual behaviour : `{}`

[index.js](https://github.com/expressjs/serve-static/blob/master/index.js#L48
)

**Comment by dougwilson** [comment]
Hello, and thank you for your issue! Yes, `console.log` does not include properties from the prototype by default. The properties are there, though, as you can see from using `console.log(opts.etag)`. So in this module there isn't any usage of `console.log`, so it is unclear what the bug is that you are reporting. Can you clarify that, perhaps can you include an example app that uses this module that misbehaves due to this?
