### ISSUE TITLE
Serving video files

### ISSUE THREAD

**Issue by sidonaldson** [expressjs/serve-static#39]
I'm hoping you can help me here.

I'm using `serve-static` to mount a media folder which contains mixed content of images, json and video. After using my web app for a few moments all the requests start to grind to a halt and chrome shows them as pending. I've got the server set up correctly with only a handful of custom routes after mounting the folder and I've reduced the timeout to 5s. I have disabled all other middleware and routes to test them for problems...

It was then I stumbled across the issue - it's the videos that are blocking everything. Am I right in thinking that serve-static is steaming the whole file? 

Is it worth looking into this or should I just prepend a middleware to prevent serving of video?

**Comment by dougwilson** [comment]
Hm, that is really weird. All this module boils down to is a lot of fancy stuff that just does `fs.createReadStream(file).pipe(res)` in the end, so it should be pretty much whatever Node.js does (though if possible, always try to serve static content from a cache, like varnish, rather than directly from your Node.js application). Can you try to replace your `serve-static` temporarily with the following, and see if it has the same behavior?
```js
var destroy = require('destroy')
var express = require('express')
var onFinished = require('on-finished')

var app = express()

app.use(fakeServeStatic(__dirname + '/public'))
app.listen(3000)

function fakeServeStatic(dir) {
  return function (req, res, next) {
    // NOTE: this is not very secure and for this diagnosis only
    var stream = fs.createReadStream(dir + req.url)
    stream.once('error', next)
    stream.pipe(res)
    onFinished(res, function (err) {
      destroy(stream)
    })
  }
}
```

But in the end, no this is not expected and if the slowdown is from Node.js, it's potentially a bug in Node.js itself. It may be worth noting what version of Node.js you're using and if you've tried any other versions.

**Comment by sidonaldson** [comment]
Thanks for the code - tested it and the same result.

Then I found this: http://stackoverflow.com/questions/16137381/html5-video-element-request-stay-pending-forever-on-chrome

Turns out Chrome might still have a long standing bug where the html5 video element hogs all the ports. I'll carry on the diagnosis and report back once confirmed.

**Comment by sidonaldson** [comment]
Yup. Confirmed as the issue (although it is supposed to be fixed)
Turns out that if you remove the html5 video or audio source before removing it from the DOM it correctly closes the pending sockets.
Sorry for the false alarm - please close

**Comment by dougwilson** [comment]
No problem! That's really weird, but I'm thankful for you following up with the case, which will help future inquiries like this here :)
