### ISSUE TITLE
mp3 and ogg files are not being served

### ISSUE THREAD

**Issue by TroyWorks** [expressjs/serve-static#44]
never mind this, turns out that I missed the load balancer in front of the node server to forward mp3 and ogg extensions.

I'm using Express 4.13.3 and the serve-static npm library. It serves static assets fine EXCEPT those with mp3 or ogg extensions. Looking at the documentation I haven't found anything to indicate that this is configurable, and others appear to be loading audio and video without issues with earlier express.

The directory is simple:
```
/public/assets/image.jpg  **works ok**
/public/assets/audio.mp3  404?!
/public/assets/audio.ogg  404?!
```
The code is simple:
```js
 app = express();
 app.use(serveStatic(__dirname + '/public'));
 app.use('/', router);
```
I can use node.js to return files but that seems a poor choice given the number of audio files. Any idea on what might be wrong?

**Comment by dougwilson** [comment]
That is really weird. I just tried it out on the latest version of Express and this module and .mp3 and .ogg files loaded just fine for me.

The only reason I can think you are getting a 404 from that code is due to the files just not existing? Can you set the environment variable `DEBUG` to `send` and paste the output you get here when you try to request one of those files?
```
export DEBUG=send
# now start your web server
```

**Comment by TroyWorks** [comment]
remove or Ignore this request, it was the haproxy loadbalancer in front of the node.js server not sending the server the mp3/ogg files.
