### ISSUE TITLE
etag for different paths

### ISSUE THREAD

**Issue by tomgrossman** [expressjs/serve-static#61]
Hi,
Is there a way to disable etag for all responses but enable them for specific paths?

Similar to your main example, I want to do something like **res.setEtag(true);**

```javascript
app.use(serveStatic(__dirname + '/public', {
  maxAge: '-1',
  etag: false,
  setHeaders: setCustomCacheControl
}))

function setCustomCacheControl(res, path) {
  if (serveStatic.mime.lookup(path) === 'image/png') {
    // Custom Cache-Control for PNG files
    res.setHeader('Cache-Control', 'public, max-age=86400');
    res.setEtag(true);
  }
}
```

**Comment by dougwilson** [comment]
Hi @tomgrossman! You can certainly do this, probably best to simply use the `etag` module directly in your `setHeaders` function, for example:
```js
var etag = require('etag'); // npm install etag

app.use(serveStatic(__dirname + '/public', {
  maxAge: '-1',
  etag: false,
  setHeaders: setCustomCacheControl
}))

function setCustomCacheControl(res, path, stat) {
  if (serveStatic.mime.lookup(path) === 'image/png') {
    // Custom Cache-Control for PNG files
    res.setHeader('Cache-Control', 'public, max-age=86400');
    res.setHeader('ETag', etag(stat));
  }
}
```

**Comment by tomgrossman** [comment]
@dougwilson thanks, but I suggest you add this option in your module as well :)

**Comment by dougwilson** [comment]
Hi @tomgrossman, I'm not sure what an interface to do such a ting would look like, but if you wanted to put together a pull request, I can definitely take a look. The purpose of `setHeaders` is to let you do most things that don't have to bloat this module with features, and came to the rescue here, allowing you to implement per-path ETags.

The goal of these modules is to be flexible and not bloated, i.e. we value convention over configuration. Rather than adding a ton of dials (options) to turn, we give you the tools to implement what you need to do using the power of JavaScript code.

**Comment by tomgrossman** [comment]
Regarding the interface - exactly like I wrote in the original question.
I understand what you mean, but I think there should be options to change all the possible headers per path. It's not bloating the module with features as they are all options and not mandatory.
Especially disabled/enable cache per path (not just ETag, Last-Modified and Expires as well) is a basic feature I would like to have.
If I'll find the time I will try to issue a pull request on it :)

**Comment by dougwilson** [comment]
Hi @tomgrossman, as far as I know, that interface is very difficult to impossible to implement, given that generating an ETag needs to know things like the path of the file, which is not stored on `res`.

> It's not bloating the module with features as they are all options and not mandatory.
 Especially disabled/enable cache per path (not just ETag, Last-Modified and Expires as well) is a basic feature I would like to have.

As far as this comment, the reason why I said that is because this is our current stance and literally the reason why the `setHeaders` option was added. If it was impossible to do your request, we would have changed something, but it's 100% possible, using the tools we built to do exactly what you are looking to do.

Perhaps your opinion is that the interface we have provided to enable/disable headers per path is not what you have expected, but that's a problem with software is that everyone has different ideas :) You're best bet is to create a fork of this module that does it the way you like and simply publish to `npm`! Or even create your own version of this module.
