### ISSUE TITLE
why serve-static did not call next() method like other middleware

### ISSUE THREAD

**Issue by kimown** [expressjs/serve-static#68]
I want to modify the response body after I use the serve-static middleware , but I am very confused why serve-static only call `next()`  when error happens, I saw other middleware's code ,like compression,cookie-session ,finally they all call next() method.

**Comment by dougwilson** [comment]
Hi @kimown, the reason this module does not call `next()` unless it's an error is because in Express and the middleware pattern, you _only_ call `next()` if you either (a) encountered an error or (b) did not write out a response body.

Since this module writes out a response body, it does not call `next()`, as this module already handled the request by sending a response. All the other examples you gave (`compression` and `cookie-session`) are not sending a response back, thus they are calling `next()` in the non-error case.
