### ISSUE TITLE
Adding Default CSP is a SemVer Major Change

### ISSUE THREAD

**Issue by andrewaustin** [expressjs/serve-static#82]
The change 9484ce6198543093ec38f679c2bd8e5b84885fbb is a breaking feature and can cause browsers to suddenly start rejecting files that previously rendered correctly. (Lost a full day because we inadvertently thought it was a misconfigured proxy.)

**Comment by dougwilson** [comment]
There are no assets on the redirect page. I'm happy to revert, but can you give an example of what it breaks? Nothing was broken in extensive testing I did, so would love to understand, since it only applies to the default redirect page.

**Comment by andrewaustin** [comment]
I'll try and come up with a recreate scenario.

**Comment by andrewaustin** [comment]
We were requesting a page that was hitting the redirect page, then programmatically injecting a number of elements, including script tags. Since this script tags were pointing to a CDN, the page would fail with those errors.

I'm not sure if this is a real issue or not, but we were able to workaround it pretty easily.  (Feel free to close)

**Comment by dougwilson** [comment]
Interesting. I thought maybe people could be doing that somehow, but wasn't sure. Usually no web browser will ever possibly render the contents on the redirect page anyway, since the browser redirects as soon as it sees the `Location` header and then just discards any body content, so I'm still not sure how adding it on the redirect would have resulted in an issue. I want to make sure that we didn't introduce something that is breaking people, can you provide all the following?

1. Complete code I can run that reproduces the issue.
2. Complete instructions for how I can reproduce the issue. I assume it will involve browsing with a web browser, so include generally the browser & version.

**Comment by andrewaustin** [comment]
It's hard to provide the code because we observed the issue in a headless selenium browser in some python code. It seems the headless browser does not follow the redirect.

**Comment by dougwilson** [comment]
Weird, because this has been tested in PhantomJS and the redirect was followed, even with the header. I want to make sure that we didn't introduce something that is breaking people, can you provide all the following?

1. Complete code I can run that reproduces the issue.
2. Complete instructions for how I can reproduce the issue. I assume it will involve browsing with a web browser, so include generally the browser & version.

**Comment by andrewaustin** [comment]
It's impossible to provide the code (mostly uninteresting, legacy python). We've worked around the change by not injecting code into the redirect page (which we shouldn't be doing in the first place).
